### ISSUE TITLE
Same Hash, Different version

### ISSUE THREAD

**Issue by jeff-hykin** [lazamar/nix-package-versions#1]
Note that `5.0.3` and `5.3.0` have the same hash (and installing turns out that its `5.3.0`)

![Screen Shot 2020-07-14 at 4 24 31 PM](https://user-images.githubusercontent.com/17692058/87478019-b521c900-c5ee-11ea-95bf-3d4468c6a460.png)

**Comment by lazamar** [comment]
When I look in the generated sqlite database and run 
```
select NAME, COMMIT_HASH, VERSION, NIXPATH from package where NAME="lua" AND CHANNEL="Nixpkgs_unstable" order by COMMIT_HASH;
```

I see
```
lua|2c9d2d65266c2c3aca1e4c80215de8bee5295b04|5.3.4|/nix/store/fzwnj2mmkg9vpakfs9anz95gf4cd673v-2c9d2d65266c2c3aca1e4c80215de8bee5295b04.tar.gz/pkgs/development/interpreters/lua-5/5.3.nix:85
lua|92a047a6c4d46a222e9c323ea85882d0a7a13af8|5.2.3|/nix/store/2ik5gydgfi326qi8d1c39dbaj96ri6qh-92a047a6c4d46a222e9c323ea85882d0a7a13af8.tar.gz/pkgs/development/interpreters/lua-5/5.2.nix:61
lua|b806e25d65421d7aa0a524ce1601f0e51099df11|5.3.0|/nix/store/8jfs0rvsa4mbi7q2y99rk523f9pk8lgr-b806e25d65421d7aa0a524ce1601f0e51099df11.tar.gz/pkgs/development/interpreters/lua-5/5.3.nix:89
lua|fa54dd346fe5e73d877f2068addf6372608c820b|5.1.5|/nix/store/asxlk3qwim1jjkad0mswn3fia7jmzv4j-fa54dd346fe5e73d877f2068addf6372608c820b.tar.gz/pkgs/development/interpreters/lua-5/interpreter.nix:101
lua|fa54dd346fe5e73d877f2068addf6372608c820b|5.2.4|/nix/store/asxlk3qwim1jjkad0mswn3fia7jmzv4j-fa54dd346fe5e73d877f2068addf6372608c820b.tar.gz/pkgs/development/interpreters/lua-5/interpreter.nix:101
lua|fa54dd346fe5e73d877f2068addf6372608c820b|5.3.5|/nix/store/asxlk3qwim1jjkad0mswn3fia7jmzv4j-fa54dd346fe5e73d877f2068addf6372608c820b.tar.gz/pkgs/development/interpreters/lua-5/interpreter.nix:101
lua|fd6600c809701543afe3e3d12f5993c4849bf72c|5.0.3|/nix/store/18bw9w6kgasg1h8q0cfbzm3va1f4yjlm-fd6600c809701543afe3e3d12f5993c4849bf72c.tar.gz/pkgs/development/interpreters/lua-5/5.0.3.nix:18
```

These nix paths don't exist in the [nixpkgs repo](https://github.com/NixOS/nixpkgs-channels/tree/nixos-unstable/pkgs/development/interpreters/lua-5). It seems like they are created when the nixpkgs derivation is evaluated and all of these versions can be installed if some parameter is included in the installation command.

- [ ] Find how to install these different versions.
- [ ] Find a way to differentiate de default version from alternative ones.
- [ ] Include version discrimination in example installation scripts

**Comment by jeff-hykin** [comment]
For the time being, do you think, for all the results with the same hash, that only the most-recent version is shown but with a red * next to it, with an explanation of the * somewhere below it

**Comment by lazamar** [comment]
This is fixed now. The commands are corrected to specify the version to be installed.
The fix indeed required rebuilding the entire database as the information needed was not available in the old format.

<img width="1080" alt="Screenshot 2020-08-25 at 16 20 45" src="https://user-images.githubusercontent.com/11493705/91193656-4062a400-e6ef-11ea-81e1-1cd94d11e51a.png">

**Comment by jeff-hykin** [comment]
Thank you!

I use the site every week, even created a command line version of it using curl because it's still way faster than `nix -qA`. Fixing this really helps my whole workflow.
