### ISSUE TITLE
Releases newer than 20.03 are missing

### ISSUE THREAD

**Issue by Gerschtli** [lazamar/nix-package-versions#12]
https://lazamar.co.uk/nix-versions/ shows in the dropdown only channels up to 20.03. All newer releases are missing.

Would it be possible to add them?

**Comment by lazamar** [comment]
Thanks for raising this.
I haven't had a lot of time lately, but I will see if I get around to doing this and updating the database this weekend.

**Comment by lazamar** [comment]
Fixed by 1f6365d
The server version deployed will include those channels.

**Comment by lazamar** [comment]
This is now live. Example: https://lazamar.co.uk/nix-versions/?channel=nixos-21.11&package=parallel
