### ISSUE TITLE
zlib-0.6.2.3 not found despite git revision flag 

### ISSUE THREAD

**Issue by carnotweat** [lazamar/nix-package-versions#19]
nix-env -i zlib-0.6.2.3 -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz
error: selector 'zlib-0.6.2.3' matches no derivations, maybe you meant:
       zlib
       zlib-ng

**Comment by lazamar** [comment]
It looks like this has something to do with #18. This should work:
```
nix-env -iA zlib -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz
```

I will update the server to incorporate the fix.

**Comment by lazamar** [comment]
The server is now updated and it should show the working installation snippet.
Thanks for the report.
