### ISSUE TITLE
Is the website down?

### ISSUE THREAD

**Issue by ssanj** [lazamar/nix-package-versions#2]
Hi, I noticed that `https://lazamar.co.uk/nix-versions/` is returning a 502 at the moment.

![Screen Shot 2020-09-24 at 3 52 55 pm](https://user-images.githubusercontent.com/366640/94106101-09161d00-fe7e-11ea-969b-7ceca0a48b84.png)

**Comment by lazamar** [comment]
It is back up! My monitoring of it failed.
