### ISSUE TITLE
npm appears to be missing 

### ISSUE THREAD

**Issue by Twiggeh** [lazamar/nix-package-versions#26]
I tried looking for nodePkgs.npm and npm (as npm is the name)
![20221111_19h21m05s_grim](https://user-images.githubusercontent.com/23149166/201404015-2a49c7a3-e7e2-40b5-91f1-26de4513d482.png)
but unfortunately they couldn't find npm :(
![20221111_19h20m04s_grim](https://user-images.githubusercontent.com/23149166/201403831-ec2205d5-8c4b-48e4-854d-d50a830ac68c.png)

**Comment by lazamar** [comment]
There is a new version of the search and `npm` can now be found.
https://lazamar.co.uk/nix-versions/?channel=nixos-unstable&package=npm

I didn't get to look into why that was happening in the previous version but should be fine now.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/11493705/224958361-d2ecd153-0df4-4fc7-b86f-26d2a5292b33.png">
