### ISSUE TITLE
database outdated

### ISSUE THREAD

**Issue by terinjokes** [lazamar/nix-package-versions#3]
It looks like the database as stopped being updated, as searching for [go](https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=go) doesn't show any of the non-betas of 1.15 that unstable has had.

**Comment by lazamar** [comment]
Thanks for the heads up! It should be up to date now.
I've had to manually run the updates locally lately because the machine in which the server is running runs out of memory before the update is completed.
