### ISSUE TITLE
Texlive not showing up

### ISSUE THREAD

**Issue by tobiasBora** [lazamar/nix-package-versions#30]
Really nice package, but if you search for `texlive.combined.scheme-full` you will not  get any result. Would it be possible to fix it by any chance? I guess the fact that it's a recursive attribute makes it more complicated to find?

**Comment by panda2134** [comment]
The same also happened for "python311Packages.matplotlib". I also guess it's related to the package being a recursive attribute.

**Comment by lazamar** [comment]
For the package to be found you need to search for the key used in the nix derivation expression for the revision.
You can find this in the nix package search website.

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/11493705/224958994-f54220c1-dc5e-4f06-b4e6-06ec5185353d.png">

Using the package name, the search finds the versions.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/11493705/224959398-0a6a3d73-6edc-4d68-8459-4210a11ee9d3.png">

**Comment by tobiasBora** [comment]
Oh good to know, thanks!
