### ISSUE TITLE
`php` does not show all the versions

### ISSUE THREAD

**Issue by drupol** [lazamar/nix-package-versions#33]
Hi,

I discovered your tool today and when [trying to find all the version of `php`](https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=php), it seems that there's a bunch of versions missing.

What is the reason of that? Am I doing something wrong?

**Comment by lazamar** [comment]
I'm not very familiar with the versions of PHP. 
The expectations is that almost all versions that at some point appeared in https://search.nixos.org/packages should appear here.

Do note that the program checks for versions in 5 week intervals. So if a package releases new versions every week, for example, we'd only pick-up every 5th of those.

**Comment by lazamar** [comment]
I'm closing this issue for now as I don't have enough information to troubleshoot the problem here. 
To open this again please say which versions are missing and show that they do or did exist at some point in nixpkgs.
