### ISSUE TITLE
No fuzzy search

### ISSUE THREAD

**Issue by ntrinite** [lazamar/nix-package-versions#37]
Seems like I need to know the exact name of the packages to search for them.
Ex: When I type "protobuf" I get all the packages with just "protobuf" in the name but if I type something like "proto", nothing comes up.

Great website overall though

**Comment by lazamar** [comment]
Yeah, I never got around to doing it.
It is performing queries in an SQLite db. 
If you'd like to give it a shot at implementing fuzzy searching I can give you pointers of where the code should go.

**Comment by lazamar** [comment]
I'll close this as a wontfix for now as I don't think fuzzy searching will be worth the effort for this project.
