### ISSUE TITLE
The nixpkgs-channels repo is deprecated and seems to no longer receive updates

### ISSUE THREAD

**Issue by ahobson** [lazamar/nix-package-versions#4]
Thank you for this tool!

The https://github.com/nixos/nixpkgs-channels repo says it is DEPRECATED in favor of https://github.com/NixOS/nixpkgs. The nixpkgs-channels repo does not seem to have received updates for 3 months or so.

Is the fix as simple as pointing to the new repo?

**Comment by ahobson** [comment]
I believe https://github.com/NixOS/nixpkgs/issues/99257 has the relevant information

**Comment by lazamar** [comment]
Thanks for raising this!
The tool is now pointing to the correct repo.

**Comment by ahobson** [comment]
Thank you! Do you also want to change [Server.hs](https://github.com/lazamar/nix-package-versions/blob/757034ce6e3890a37cc96cafd710fbb2c871f547/src/App/Server.hs#L288) ?

**Comment by lazamar** [comment]
Ah, just fixed that. Thanks!
