### ISSUE TITLE
Update planned ?

### ISSUE THREAD

**Issue by 573** [lazamar/nix-package-versions#43]
I relied on this service for now, thank you for sharing this with the community.

I saw the latest entries for an example package (https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=ghc) being 23.11 / unstable from around april.

Is there a chance to get 24.05 links as well ?

[Workaround example](https://hydra.nixos.org/eval/1807257?filter=nixpkgs.ghc.x86_64-linux&compare=1807228&full=#tabs-inputs)

Glad if I could help with anything.

**Comment by 573** [comment]
#44

**Comment by lazamar** [comment]
Thanks for the PR. I'll update the website as soon as I get some time. Maybe tonight.

**Comment by lazamar** [comment]
It is updated now. The binary with the new channels is running and the database was updated.
