### ISSUE TITLE
Fix GitHub Actions compilation

### ISSUE THREAD

**Issue by lazamar** [lazamar/nix-package-versions#5]
Changes to GitHub Actions are making CI fail.
There is a link in the failure to instructions on how to make it work.

**Comment by elikoga** [comment]
The link in the failure consists of instructions to build around the issue.

`actions/setup-haskell@v1.1` is deprecated as seen in https://github.com/actions/setup-haskell

We should use `haskell/actions/setup@v1` as seen in https://github.com/haskell/actions/issues/25

I will submit a pull request to rectify this
