### ISSUE TITLE
No updates since 2021-01-04

### ISSUE THREAD

**Issue by ahobson** [lazamar/nix-package-versions#7]
Your tool is so amazing that I use it all the time. As far as I can tell, I don't see any updates since 2021-01-04.

For example, go 1.15.7 was released on Jan 20 and 1.15.8 on Feb 14 but neither show up in the [package search for go](https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=go)

Thank you for any help you can provide

**Comment by lazamar** [comment]
Thanks for bringing it up. It is up to date now. The latest go release available is `2021-02-08`.
The automatic updating of the database is unfortunately not working at the moment as the Digital Ocean droplet in which the server is running doesn't have enough memory to perform the database update.
I need to come up with a cheap solution to have the script run in a capable enough server every 5 weeks or so.
