### ISSUE TITLE
show fetchTarball as well as fetchGit

### ISSUE THREAD

**Issue by smasher164** [lazamar/nix-package-versions#8]
First of all, thank you for making this tool! This has saved me countless hours of effort.

Second, on an environment without Git installed, nix will complain `no such file or directory git`. I ended up using `fetchTarball` instead for this reason. I'd like to request that `fetchTarball` be shown on the site as well, and preferably prioritized so that users end up copying the right thing.

**Comment by devinalvaro** [comment]
Was going to suggest this as well. `fetchGit` clones the whole repo so it often takes a significantly longer time than just fetching the tarball. Plus, the instruction to install with `nix-env` already uses the link to tarball, so it's a nicer transition IMO.
