### ISSUE TITLE
OS/Architecture Difference 

### ISSUE THREAD

**Issue by jeff-hykin** [lazamar/nix-package-versions#9]
Hi @lazamar 

I'd like to help, and I'm trying to figure out how you're currently handling differences such as operating systems and architectures when querying nixpkg. But, honestly I can't find how/where you're contacting the nixpkg source. Normally I'd have a local nixpkg repo, and querying it would only return packages available for my OS/Arch, but it seems you get around that somehow.

My guess is it's somewhere [here](https://github.com/lazamar/nix-package-versions/blob/3b2caa78b7e130619818e5afa8b549b23377ac30/src/Nix/Versions.hs#L78) or [here](https://github.com/lazamar/nix-package-versions/blob/3b2caa78b7e130619818e5afa8b549b23377ac30/src/Control/Monad/Revisions.hs#L87) but I still don't see the URL to nixpkgs anywhere so I'm not sure how it's being done.

Any guidance would be helpful.

**Comment by lazamar** [comment]
Cool, so there are two parts to the system. One is collecting data about packages and revisions and storing them in a database. The other one is using that database to perform queries.

To collect the data we 
- Choose some commits from a branch of https://github.com/NixOS/nixpkgs
- Download the expressions for that revision ([here](https://github.com/lazamar/nix-package-versions/blob/3b2caa78b7e130619818e5afa8b549b23377ac30/src/Nix/Revision.hs#L141-L145))

At https://lazamar.co.uk/nix-versions/ people select a branch to search for packages available in commits from that branch.

In neither of these phases actual application artefacts are handled, only Nix expressions, which are recipes for how to build packages and may or may not include architecture-specific constraints. Architectural concerns are handled by Nix when building the expressions, this project only collects the expressions and makes them available.

With regards to the OS, expressions for different OSs are kept in different channels
- `nixpkgs-unstable` for Linux
- `nixos-*` for Nixos
- `nixpkgs-*-darwin` for OSX 

I hope this helped to clarify things, if you still have questions feel free to reopen the ticket.

**Comment by jeff-hykin** [comment]
Oh interesting, that helps a lot, and is a much better way of doing it. When I was trying to build one a version logging system, I was checking out different commits and using the nix command line tool, which automatically evaluates the Arch/OS (which was obviously problematic).

When you're extracting the nix expressions, is there a Haskell library that's doing some of the work, or is there a nix command line option I'm unaware of, or is it simply a folder/file naming pattern (like getting all the `default.nix` files)?

**Comment by jeff-hykin** [comment]
My goal is to make the search system more complete, both by spending a lot more CPU cycles going over every commit, but also things like allowing people to publish their own packages, where they're searchable to the public but don't need a PR against the nixpkg repo (the code would be hosted in their own repo).

**Comment by jeff-hykin** [comment]
> expressions for different OSs are kept in different channels

I guess this is part I'm still confused about (although a lot has been cleared up by that link to downloading the expressions, thank you).

@lazamar 
1. Wouldn't the `nix-env -qaP --json` in [there](https://github.com/lazamar/nix-package-versions/blob/3b2caa78b7e130619818e5afa8b549b23377ac30/src/Nix/Revision.hs#L142) be using the host OS for that query?
2. I think I can make progress if I can solve my confusion between channels vs branches
  - the master branch is equivlent to unstable right?
  - Given this:
     >    `nixpkgs-unstable` for Linux
     >    `nixos-*` for Nixos
     >    `nixpkgs-*-darwin` for OSX

    does this mean `master` is only for Linux?
    is there no `nixpkg-darwin-unstable`?
